FROM envoyproxy/envoy:v1.13.0

COPY envoy-sidecar.yaml /etc/envoy.yaml
COPY docker-sidecar-entrypoint.sh /
COPY sds-linux-amd64 /usr/local/bin/sds

RUN chmod 500 /docker-sidecar-entrypoint.sh

RUN apt-get update && \
    apt-get install gettext -y

ENTRYPOINT ["/docker-sidecar-entrypoint.sh"]